---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2023/6/30 14:45
---
--1.参数列表
--1.1优惠券id
local voucherId = ARGV[1]
--1.2用户id
local userId = ARGV[2]
--2.数据key
--2.1库存key
local stockKey= 'seckill:stock:'..voucherId
--2.2订单id
local orderKey= 'seckill:order:'..voucherId
--脚本业务
--3.1判断库存是否充足get stockKey
local stock = tonumber(redis.call('get', stockKey))
if stock and stock <= 0 then
    -- 库存不足返回1
    return 1
end
--3.2判断用户是否下单
if(redis.call('sismember',orderKey,userId) == 1) then
    --3.3存在，说明是重复下单，返回2
    return 2
end
--3.4扣库存
redis.call('incrby',stockKey,-1)
--3.5说明
redis.call('sadd',orderKey,userId)
--成功返回0
return 0